name: plateforme_de_gestion_quincaillerie
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  flutter_svg: ^0.22.0
  percent_indicator: ^4.2.3
  provider: ^5.0.0

  json_annotation: ^4.0.1
  json_serializable: ^4.1.2
  build_runner: ^2.0.3

  table_calendar: ^3.0.0
  flutter_screenutil: ^5.0.0+2
  smooth_page_indicator: ^0.3.0-nullsafety.0
  colorize_text_avatar: ^1.0.2
  intl: ^0.18.1
  syncfusion_flutter_charts: ^22.1.37
  fl_chart: ^0.63.0
  syncfusion_flutter_datepicker: ^22.1.37
  http: ^1.1.0
  fluttertoast: ^8.2.2
  syncfusion_flutter_datagrid: ^22.1.37
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/slides/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

